### PR TITLE
fixed ieCompat option default

### PR DESCRIPTION
**Pull request by akosicki**

### CODE REVIEW

**Comment by huntc** [comment]
So lessc is iecompat by default then?

**Comment by akosicki** [comment]
@huntc the problem is it's always ieCompat, no matter what you set in the build.sbt 
`option.ieCompat || true` roughly means just `true`

**Comment by huntc** [comment]
Hi @akosicki,

Thank you for your contribution.  Would you mind signing our CLA?

http://www.typesafe.com/contribute/cla

Thanks!

**Comment by akosicki** [comment]
ok

**Comment by akosicki** [comment]
@huntc, signed

**Comment by huntc** [comment]
Thanks!

**Pull request merged**
