### PR TITLE
Update to LESS 2.5 [closes #53]

### LINKED ISSUE #53: Updgrade to less 2.0
Less 2.0.0 was released on Nov 11: https://github.com/less/less.js/blob/master/CHANGELOG.md#200

### PR DESCRIPTION
**Pull request by yatskevich**

### CODE REVIEW

**Comment by yatskevich** [comment]
@jroper Would you like to push your work separately?

**Comment by jroper** [comment]
@yatskevich yes, if you could remove everything to do with bintray and the sbt js-engine/web plugin upgrades out this, that would be great.

**Comment by yatskevich** [comment]
Updated:
- your initial commit was cleaned up from bintray related changes;
- workaround for source map for empty less file was implemented.

**Comment by jroper** [comment]
w00t!  Thanks!

**Comment by jroper** [comment]
sbt-less has been released as 1.1.0.

**Pull request merged**
