### PR TITLE
support disabling sourceMap generation

### PR DESCRIPTION
**Pull request by jtjeferreira**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @jtjeferreira,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by jtjeferreira** [comment]
CLA signed

**Comment by wsargent** [comment]
Hi @jtjeferreira could you add some documentation to the readme about this flag? https://github.com/sbt/sbt-less/blob/master/README.md

**Comment by jtjeferreira** [comment]
hi @wsargent. the flag already exists and is documented:

> sourceMap: Outputs a v3 sourcemap.

**Pull request merged**
