### PR TITLE
Bump up less-node to 3.8.1

### PR DESCRIPTION
**Pull request by chungonn**
This is to update sbt-less to use lessc 3.8.1. Have updated all the libraries including the sbt.version

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @chungonn,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by chungonn** [comment]
I have signed the CLA.

**Comment by jroper** [comment]
We'll have to fix CI before this can be merged, I guess it's failing because travis doesn't support oracle-jdk8 anymore. The less integration is quite fragile when it comes to upgrades, upgrading less usually breaks it, until we see CI pass, it's far too dangerous to merge this.

**Comment by chungonn** [comment]
Noted with thanks. BTW, after the changes, i did a 'sbt test' for the subproject sbt-less-plugin-tester, it reported as success.

**Comment by jroper** [comment]
`sbt test` only runs the unit tests. `sbt scripted` runs the full integration test suite.

**Comment by jroper** [comment]
OK, I've fixed CI, if you rebase on master and update this PR, CI should run.

**Comment by chungonn** [comment]
Thanks James! I was not aware about updating the CI scripts. Will be mindful about it the next time :). Will close this PR and merge your work and raise another PR again.

**Comment by jroper** [comment]
No need to open a new PR, and it wasn't your fault about the CI scripts, they just broke when travis changed something and no one has submitted a PR for quite some time so we didn't notice.

You can reopen this PR if you want, it's updated. And, it's failing, with the following error:

```
[info] com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: module.js:550
[info]     throw err;
[info]     ^
[info] 
[info] Error: Cannot find module 'less-plugin-clean-css'
[info]     at Function.Module._resolveFilename (module.js:548:15)
[info]     at Function.Module._load (module.js:475:25)
[info]     at Module.require (module.js:597:17)
[info]     at require (internal/module.js:11:18)
[info]     at /tmp/sbt_bfe373a8/clean-css/project/target/less/lessc.js:61:38
[info]     at Array.forEach (<anonymous>)
[info]     at /tmp/sbt_bfe373a8/clean-css/project/target/less/lessc.js:43:24
[info]     at Object.<anonymous> (/tmp/sbt_bfe373a8/clean-css/project/target/less/lessc.js:155:3)
[info]     at Module._compile (module.js:653:30)
[info]     at Object.Module._extensions..js (module.js:664:10)
```

**Pull request closed without merging**
